services:
  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user-service"]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    container_name: liquibase
    image: liquibase/liquibase:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db:5432/postgres
      - LIQUIBASE_COMMAND_USERNAME=postgres
      - LIQUIBASE_COMMAND_PASSWORD=root
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=db/changelog/db.changelog-master.yaml
    volumes:
      - ./src/main/resources/db:/liquibase/db
    command: "update"

  app:
    container_name: wallet-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - liquibase
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_LIQUIBASE_ENABLED=false
    ports:
      - "8081:8081"

volumes:
  postgres-data: