spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    url: ${LIQUIBASE_COMMAND_URL}
    user: ${LIQUIBASE_COMMAND_USERNAME}
    password: ${LIQUIBASE_COMMAND_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081
